### ISSUE TITLE
We haven't gotten past the brainstorming phase

### ISSUE THREAD

**Issue by BillyBobJoe2756** [Teddygat0r/HackCupertino#1]
Arthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is baldArthur is bald

**Comment by BillyBobJoe2756** [comment]
Ok, now for actual information. Insofar, we have no idea, and should just make a bare bones website in the meantime.

**Comment by Teddygat0r** [comment]
Closing irrelevant issue
